name: 🚀 Deploy PROD

on:
  workflow_dispatch:
    inputs:
      prod_india:
        description: "Deploy to prod-india?"
        type: choice
        options: [no, yes]
        default: no

      prod_canada:
        description: "Deploy to prod-canada?"
        type: choice
        options: [no, yes]
        default: no

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - env: prod-india
            input: prod_india

          - env: prod-canada
            input: prod_canada

    steps:
      - name: 🧾 Checkout
        uses: actions/checkout@v4

      - name: 🔍 Debug Inputs
        run: |
          echo "prod_india: ${{ github.event.inputs.prod_india }}"
          echo "prod_canada: ${{ github.event.inputs.prod_canada }}"
          echo "Current: ${{ matrix.env }}"

      - name: 🚀 Deploy PROD
        if: github.event.inputs[matrix.input] == 'yes'
        run: |
          echo "✅ Deploying to ${{ matrix.env }}"
